export enum HL {
  artist = 'artist',
  contentType = 'content type',
  deliveryMethod = 'delivery method',
  product = 'product',
  distributor = 'distributor',
  store  = 'store',
  service = 'service',
  isrc = 'isrc',
  label = 'label',
  periodFrom = 'period from',
  salesStartDate = 'sales start date',
  periodTo = 'period to',
  salesEndDate = 'sales end date',
  quantity = 'quantity',
  totalPlays = 'total plays',
  releaseTitle = 'release title',
  albumName = 'album name',
  release = 'release',
  revenue = 'revenue',
  amount = 'amount',
  territory = 'territory',
  countryIso = 'country iso',
  trackTitle = 'track title',
  trackName = 'track name',
  track = 'track',
  date = 'date',
  transactionDate = 'transaction date',
  upc = 'upc',
  eanUpc = 'ean/upc',
  countryName = 'country name',
  totalDownloads = 'total downloads',
  amountCurrency = 'amount currency',

  catNo = 'cat. no',
  suitebeatsComp = 'suitebeats comp.'
}
